COMP: Refiner: Fix build error using "std::abs" instead of "abs"
This commit fixes linux build error like the following:

  /path/to/SkeletalRepresentationRefiner/Logic/vtkSlicerSkeletalRepresentationInterpolater.cpp:74:25: error: ‘abs’ was not declared in this scope
     if(abs(u - halfDist ) <= tolerance && abs(v - halfDist) <= tolerance)
                         ^